os: linux
dist: trusty
language: node_js
node_js:
- 8
script:
- npm run lint
- npm run ci:format
- npm run build
- npm run test
- npm run test:integration
after_success:
- npm run ci:coverage
- scripts/update.sh
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
