os:
- linux
before_install:
- sudo apt-get install xsel
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run format:guard
- npm run build
- npm run test
- npm run test:integration
after_success:
- scripts/update.sh
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
