language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- npm run lint
- npm run format:guard
- npm run test
- npm run build
after_success:
- chmod +x .travis/update.sh && .travis/update.sh
